"""Initial schema

Revision ID: 2283644ecd5f
Revises: 
Create Date: 2026-01-31 12:33:07.338524+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2283644ecd5f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gyms',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('subscription_status', sa.Enum('TRIAL', 'ACTIVE', 'EXPIRED', 'SUSPENDED', name='subscription_status', create_constraint=True), nullable=False),
    sa.Column('subscription_start', sa.Date(), nullable=True),
    sa.Column('subscription_end', sa.Date(), nullable=True),
    sa.Column('setup_fee_paid', sa.Boolean(), nullable=False),
    sa.Column('billing_cycle', sa.Enum('MONTHLY', 'YEARLY', name='billing_cycle', create_constraint=True), nullable=True),
    sa.Column('gst_number', sa.String(length=20), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gyms_email'), 'gyms', ['email'], unique=True)
    op.create_index(op.f('ix_gyms_slug'), 'gyms', ['slug'], unique=True)
    op.create_index(op.f('ix_gyms_subscription_status'), 'gyms', ['subscription_status'], unique=False)
    op.create_table('members',
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('member_code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('alternate_phone', sa.String(length=15), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender', create_constraint=True), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=15), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('joined_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gym_id', 'phone', name='uq_member_gym_phone')
    )
    op.create_index('idx_member_gym_phone', 'members', ['gym_id', 'phone'], unique=False)
    op.create_index('idx_member_joined_date', 'members', ['gym_id', 'joined_date'], unique=False)
    op.create_index(op.f('ix_members_gym_id'), 'members', ['gym_id'], unique=False)
    op.create_table('plans',
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_plan_gym_active', 'plans', ['gym_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_plans_gym_id'), 'plans', ['gym_id'], unique=False)
    op.create_table('users',
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('role', sa.Enum('OWNER', 'MANAGER', 'STAFF', name='user_role', create_constraint=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gym_id', 'email', name='uq_user_gym_email')
    )
    op.create_index(op.f('ix_users_gym_id'), 'users', ['gym_id'], unique=False)
    op.create_table('attendance',
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('marked_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_attendance_daily', 'attendance', ['gym_id', 'check_in_time'], unique=False)
    op.create_index('idx_attendance_member', 'attendance', ['member_id', 'check_in_time'], unique=False)
    op.create_index(op.f('ix_attendance_gym_id'), 'attendance', ['gym_id'], unique=False)
    op.create_index(op.f('ix_attendance_member_id'), 'attendance', ['member_id'], unique=False)
    op.create_table('memberships',
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('amount_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'PAUSED', 'CANCELLED', name='membership_status', create_constraint=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_membership_expiry', 'memberships', ['gym_id', 'status', 'end_date'], unique=False)
    op.create_index('idx_membership_gym_dates', 'memberships', ['gym_id', 'start_date', 'end_date'], unique=False)
    op.create_index('idx_membership_member_status', 'memberships', ['member_id', 'status'], unique=False)
    op.create_index(op.f('ix_memberships_gym_id'), 'memberships', ['gym_id'], unique=False)
    op.create_index(op.f('ix_memberships_member_id'), 'memberships', ['member_id'], unique=False)
    op.create_index(op.f('ix_memberships_plan_id'), 'memberships', ['plan_id'], unique=False)
    op.create_index(op.f('ix_memberships_status'), 'memberships', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.Enum('EXPIRY_REMINDER', 'PAYMENT_DUE', 'WELCOME', 'CUSTOM', name='notification_type', create_constraint=True), nullable=False),
    sa.Column('channel', sa.Enum('WHATSAPP', 'SMS', 'EMAIL', name='notification_channel', create_constraint=True), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='notification_status', create_constraint=True), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_member', 'notifications', ['gym_id', 'member_id'], unique=False)
    op.create_index('idx_notification_pending', 'notifications', ['status', 'scheduled_at'], unique=False)
    op.create_index(op.f('ix_notifications_gym_id'), 'notifications', ['gym_id'], unique=False)
    op.create_index(op.f('ix_notifications_member_id'), 'notifications', ['member_id'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('membership_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_mode', sa.Enum('CASH', 'UPI', 'CARD', 'BANK_TRANSFER', 'OTHER', name='payment_mode', create_constraint=True), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('reference_number', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('received_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_date', 'payments', ['gym_id', 'payment_date'], unique=False)
    op.create_index('idx_payment_member', 'payments', ['gym_id', 'member_id', 'payment_date'], unique=False)
    op.create_index('idx_payment_mode', 'payments', ['gym_id', 'payment_mode', 'payment_date'], unique=False)
    op.create_index(op.f('ix_payments_gym_id'), 'payments', ['gym_id'], unique=False)
    op.create_index(op.f('ix_payments_member_id'), 'payments', ['member_id'], unique=False)
    op.create_index(op.f('ix_payments_membership_id'), 'payments', ['membership_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_membership_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_member_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_gym_id'), table_name='payments')
    op.drop_index('idx_payment_mode', table_name='payments')
    op.drop_index('idx_payment_member', table_name='payments')
    op.drop_index('idx_payment_date', table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_member_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_gym_id'), table_name='notifications')
    op.drop_index('idx_notification_pending', table_name='notifications')
    op.drop_index('idx_notification_member', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_memberships_status'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_plan_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_member_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_gym_id'), table_name='memberships')
    op.drop_index('idx_membership_member_status', table_name='memberships')
    op.drop_index('idx_membership_gym_dates', table_name='memberships')
    op.drop_index('idx_membership_expiry', table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_attendance_member_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_gym_id'), table_name='attendance')
    op.drop_index('idx_attendance_member', table_name='attendance')
    op.drop_index('idx_attendance_daily', table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_users_gym_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_plans_gym_id'), table_name='plans')
    op.drop_index('idx_plan_gym_active', table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_members_gym_id'), table_name='members')
    op.drop_index('idx_member_joined_date', table_name='members')
    op.drop_index('idx_member_gym_phone', table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_gyms_subscription_status'), table_name='gyms')
    op.drop_index(op.f('ix_gyms_slug'), table_name='gyms')
    op.drop_index(op.f('ix_gyms_email'), table_name='gyms')
    op.drop_table('gyms')
    # ### end Alembic commands ###
