"""Add demo requests

Revision ID: e51c1cbe7902
Revises: 2283644ecd5f
Create Date: 2026-02-01 08:11:32.768602+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e51c1cbe7902'
down_revision: Union[str, None] = '2283644ecd5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_requests',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gym_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('locality', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demo_requests_city'), 'demo_requests', ['city'], unique=False)
    op.create_index(op.f('ix_demo_requests_phone'), 'demo_requests', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demo_requests_phone'), table_name='demo_requests')
    op.drop_index(op.f('ix_demo_requests_city'), table_name='demo_requests')
    op.drop_table('demo_requests')
    # ### end Alembic commands ###
